#postgresql:
#  container_name: postgre_db
#  image: postgres:latest
#  restart: always
#  ports:
#    - "5432:5432"
#  volumes:
#    - ./database/main/:/var/lib/postgresql/
#    - ./database/init/:/docker-entrypoint-initdb.d/
#
#  environment:
#    POSTGRES_USER: 01user
#    POSTGRES_PASSWORD: 01password
#    POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
version: '2'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/main/:/var/lib/postgresql/
      - ./database/init/:/docker-entrypoint-initdb.d/

    environment:
      POSTGRES_USER: 01user
      POSTGRES_PASSWORD: 01password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"


#dropwizard:
#  image: adoptopenjdk/openjdk12:latest
#  ports:
#    - "5432:5432"
#    - "8080:8080"
#    - "8090:8090"
#  volumes:
#    - ./build/libs/:/dropwizard/bin/
#    - ./:/dropwizard/
#  command: ["java", "-jar", "-Done-jar.silent=true", "/dropwizard/bin/3dmodel-1.0-all.jar", "server", "/dropwizard/three.yml"]
